spring.application.name=nextword
# ==========================================
# CONEXIÓN A ORACLE CLOUD (PREPARADO PARA EQUIPO Y AWS)
# ==========================================
# Usamos variables de entorno para la ruta del wallet y credenciales
spring.datasource.url=jdbc:oracle:thin:@sistemadecapacitacion_high?TNS_ADMIN=${RUTA_WALLET_ORACLE}
spring.datasource.username=${USUARIO_ORACLE}
spring.datasource.password=${PASSWORD_ORACLE}

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ===============================
# CONFIGURACIÓN DE CORREO (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=teamnextword@gmail.com
spring.mail.password=crfwwaqzgxulsrtn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true